version: '3.9'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # for dev testing in containers. Hot Reload

  web:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app  # for dev testing in containers. Hot Reload
      - /app/node_modules


volumes:
  pgdata:
